<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Membaca Cerita - Naratia</title>
    
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Merriweather:wght@300;400;700&display=swap" rel="stylesheet">
    
    <style>
        body { background-color: #02040f; color: #e2e8f0; font-family: 'Inter', sans-serif; }
        .story-content { font-family: 'Merriweather', serif; line-height: 2; font-size: 1.125rem; }
        .no-scrollbar::-webkit-scrollbar { display: none; }
    </style>
</head>
<body class="min-h-screen flex flex-col no-scrollbar">

    @php
        $user = session('user');
        $charName = $user->character_name ?? 'Pembaca'; 
        
        $storyId = request()->segment(3) ?? '1';
        $currentChapter = (int) request()->query('chapter', 1);

        // DATABASE SEMUA CERITA
        $story = [
            '1' => [
                'title' => 'Rahasia Langit',
                'author' => 'Emi Thasorn',
                'cover' => 'https://picsum.photos/seed/naratia2/150/220',
                'chapters' => [
                    1 => ['title' => 'Bab 1 | Bintang Jatuh', 'content' => "Malam itu sangat dingin, angin berhembus menusuk tulang. yn merapatkan jaketnya sambil menatap langit malam dari balkon kamar yang sepi. Tidak ada bintang yang menghiasi angkasa, hanya awan kelabu yang menggulung pelan. Keheningan malam itu tiba-tiba pecah ketika sekelebat cahaya terang benderang menyayat langit dan jatuh berdebum tepat di halaman belakang rumah yn.<br><br>Asap tipis mengepul dari kawah kecil di antara hamparan rumput. Dengan jantung berdebar kencang, yn memberanikan diri menuruni tangga dan mendekati lokasi jatuhnya benda asing tersebut. Langkah yn terhenti seketika. Di tengah kawah itu, bukan meteor yang yn temukan, melainkan seorang pemuda yang terkapar tak sadarkan diri.<br><br>Pakaian yang dikenakan pemuda itu sangat aneh, memancarkan pendaran cahaya kebiruan yang redup. yn menelan ludah, bingung harus berbuat apa. Namun, insting yn mengatakan bahwa pemuda ini butuh bantuan. Dengan susah payah, yn memapah tubuh pemuda asing itu masuk ke dalam rumah. yn membaringkannya di sofa ruang tamu, mengambil kotak P3K, dan mulai membersihkan luka di pelipis pemuda itu. yn sama sekali tidak menyadari bahwa keputusan beraninya malam ini akan mengubah takdir kehidupannya untuk selamanya."],
                    2 => ['title' => 'Bab 2 | Namanya Langit', 'content' => "Keesokan harinya, cahaya matahari pagi mengintip dari balik tirai jendela. Pemuda asing itu akhirnya membuka matanya, mengerjap bingung melihat langit-langit rumah yang asing. yn, yang ketiduran di kursi sebelah sofa, terperanjat bangun saat mendengar suara erangan pelan. 'Kau sudah sadar?' tanya yn hati-hati, menjaga jarak aman.<br><br>Pemuda itu bangkit perlahan, menatap kedua tangannya sendiri lalu menatap yn dengan sorot mata yang sulit diartikan. Dia menyebut dirinya 'Langit'. Nama yang aneh, pikir yn, tapi entah kenapa sangat cocok dengan penampilannya yang misterius. yn mencoba menawarkannya sarapan berupa roti bakar dan susu hangat yang baru saja yn buat.<br><br>Namun, pemuda ini sama sekali tidak tahu apa-apa tentang bumi. Dia mengendus roti itu dengan curiga, seolah itu adalah benda beracun. 'Tempat apa ini, yn?' tanyanya bingung sambil menunjuk ke arah televisi yang sedang menyiarkan berita pagi. Matanya membelalak melihat orang-orang di dalam kotak kaca tersebut. yn menghela napas panjang, mengusap wajahnya yang kusam. yn menyadari bahwa mengajari Langit tentang cara bertahan hidup di bumi akan menjadi tugas yang sangat merepotkan, sekaligus menguji kesabaran yn hingga batas maksimal."],
                    3 => ['title' => 'Bab 3 | Menyamar', 'content' => "Libur akhir pekan telah usai, dan yn terpaksa membawa Langit ke sekolah karena tidak berani meninggalkannya sendirian di rumah. Segala macam benda elektronik di rumah bisa meledak jika Langit salah memencet tombol. yn menyamarkan Langit sebagai sepupu jauh dari luar kota, memberikannya seragam bekas milik kakak yn yang kebetulan pas di badan Langit.<br><br>Di dalam kelas, kehadiran murid baru yang tampan dan canggung ini langsung menarik perhatian. Namun, Langit sama sekali tidak mempedulikan tatapan siswi lain; matanya terus saja menatap lekat ke arah yn. Sepanjang jam pelajaran Matematika, Langit tak berhenti memperhatikan bagaimana cara yn menulis.<br><br>'Kenapa kau terus melihatku dari tadi?' bisik yn kesal, merasa risih karena teman-teman sekelas mulai berbisik-bisik. Langit menopang dagunya, menatap mata yn dengan polos. 'Karena dari semua hal aneh di planet ini, kau adalah satu-satunya yang lebih bersinar dari bintang,' jawab Langit santai. Mendengar kalimat itu, pipi yn seketika bersemu merah padam. yn buru-buru menyembunyikan wajahnya di balik buku tebal, merutuki detak jantungnya sendiri yang tiba-tiba berpacu di luar kendali."],
                    4 => ['title' => 'Bab 4 | Kekuatan Tersembunyi', 'content' => "Sepulang sekolah, yn mengajak Langit melewati jalan pintas di sebuah gang sempit untuk menghindari keramaian. Sialnya, mereka dicegat oleh segerombolan preman daerah yang memang sering memalak anak sekolah. yn ketakutan setengah mati, kakinya gemetar melihat pisau lipat yang dimainkan oleh pemimpin preman tersebut.<br><br>'Serahkan tas dan dompet kalian, atau gadis ini akan terluka,' ancam preman itu sambil melangkah maju ke arah yn. Sebelum tangan kotor preman itu menyentuh bahu yn, Langit sudah lebih dulu melangkah maju, memposisikan dirinya sebagai tameng pelindung yn. Tatapan polos Langit seketika berubah menjadi tajam dan dingin mematikan.<br><br>'Jangan pernah berani menyentuhnya,' desis Langit. Dengan satu jentikan jari yang sangat pelan, pusaran angin kencang tiba-tiba berhembus entah dari mana. Angin itu menghantam para preman layaknya pukulan tak kasat mata, mementalkan mereka hingga menabrak dinding bata dan jatuh pingsan. yn terpaku di tempat, napasnya tertahan. Matanya membulat tak percaya melihat fenomena tak masuk akal di depan matanya. Langit berbalik menatap yn, mengulurkan tangannya dengan lembut. 'Ayo pulang, yn.'"],
                    5 => ['title' => 'Bab 5 | Sang Pewaris', 'content' => "Begitu sampai di kamar, yn langsung mengunci pintu rapat-rapat. yn menuntut penjelasan dari kejadian gila tadi sore. 'Siapa kau sebenarnya, Langit? Manusia tidak bisa melakukan hal seperti tadi!' tanya yn dengan suara bergetar, setengah takut dan setengah penasaran. yn menatap Langit lekat-lekat, mencari kebohongan di matanya.<br><br>Langit terdiam cukup lama. Dia menunduk sedih, seolah mengingat kenangan yang menyakitkan. Perlahan, dia mengangkat wajahnya dan menatap mata yn. 'Aku bukan manusia, yn. Aku adalah pewaris tahta dari rasi bintang utara. Kami adalah ras penjaga keseimbangan galaksi.'<br><br>yn ternganga, mencoba mencerna rentetan kalimat yang terdengar seperti naskah film fiksi ilmiah. 'Lalu... kenapa kau bisa jatuh ke halaman belakang rumahku?' cecar yn. Langit tersenyum getir. 'Aku dibuang, yn. Aku menolak perintah ayahku untuk memimpin perang pemusnahan massal melawan ras nebula. Karena pembangkanganku, ingatanku sempat disegel dan aku dilempar ke dimensi bumi. Dan entah kenapa, gravitasiku justru tertarik ke arahmu, yn.'"],
                    6 => ['title' => 'Bab 6 | Terbang Bersama', 'content' => "Malam itu, setelah obrolan panjang yang menguras pikiran, Langit mengajak yn naik ke atap gedung tertinggi di tengah kota. Angin malam berhembus kencang menerpa wajah mereka. Lampu-lampu kota di bawah sana terlihat seperti hamparan bintang buatan. yn berdiri di tepi atap, merasa sedikit pusing melihat ketinggian yang curam.<br><br>Langit perlahan meraih pinggang yn dan menggenggam erat satu tangan yn yang mulai dingin. 'Pegang erat-erat dan percaya padaku, yn,' bisik Langit tepat di telinga yn. Sebelum yn sempat protes, Langit melangkah maju, menjatuhkan diri mereka berdua dari atas gedung pencakar langit tersebut.<br><br>yn menjerit histeris, memejamkan mata rapat-rapat. Namun, alih-alih terjatuh menghantam aspal, gravitasi seolah kehilangan kuasanya. yn membuka mata dan menyadari bahwa mereka sedang melayang. Tidak, mereka terbang. Langit membawa yn melesat menembus awan, menari di udara bebas layaknya burung. Ketakutan yn menguap, digantikan oleh tawa lepas yang menggema di langit malam. Malam itu, yn merasa hidupnya benar-benar telah berubah menjadi keajaiban yang tak ternilai."],
                    7 => ['title' => 'Bab 7 | Firasat Buruk', 'content' => "Sejak malam ajaib di atas awan itu, yn menyadari bahwa perasaannya mulai tumbuh subur. Kehadiran Langit bukan lagi beban, melainkan kenyamanan yang tak tergantikan. Langit selalu ada, melindungi yn dari hal sekecil apa pun, bahkan dari rintik hujan yang mencoba membasahi rambut yn. Mereka sering menghabiskan waktu berdua di balkon rumah, berbagi cerita tentang bumi dan galaksi.<br><br>Namun, kebahagiaan yn mulai diwarnai kegelisahan. Bayang-bayang masa lalu Langit mulai mengejar mereka. Beberapa malam terakhir, yn sering melihat kilatan cahaya merah aneh yang melintas di langit kota. Bukan meteor, melainkan sesuatu yang bergerak dengan pola teratur.<br><br>Langit tampak semakin murung setiap kali melihat kilatan merah tersebut. 'Mereka menemukanku, yn,' gumam Langit suatu malam dengan rahang mengeras. Bintang jatuh berwarna merah itu adalah sinyal pencarian dari pasukan elit rasi bintang. Firasat buruk menyelimuti hati yn. yn tahu, kedamaian mereka akan segera berakhir dalam hitungan hari."],
                    8 => ['title' => 'Bab 8 | Serangan Bayangan', 'content' => "Ketakutan yn akhirnya menjadi kenyataan. Sore itu, saat mereka sedang berjalan berdua melintasi taman kota yang sepi, langit senja tiba-tiba meredup. Suhu udara anjlok drastis. Dari balik bayangan pepohonan, muncul tiga sosok berjubah hitam dengan mata menyala merah. Mereka melayang beberapa inci di atas tanah.<br><br>'Serahkan pangeran pengkhianat kami, manusia!' teriak salah satu sosok bayangan itu kepada yn. Suaranya menggema, seolah datang dari segala arah. yn mematung, kakinya gemetar hebat tak bisa digerakkan. Langit langsung menarik yn ke belakang punggungnya yang bidang, memasang kuda-kuda bertarung.<br><br>'Lari, yn! Sekarang! Tinggalkan aku di sini!' perintah Langit dengan nada membentak, sesuatu yang belum pernah dia lakukan sebelumnya. Namun yn menggeleng keras, air mata mulai menggenang di pelupuk matanya. Pertarungan tak seimbang pun pecah. Energi kosmik berbenturan, menghancurkan pepohonan di sekitar taman. yn hanya bisa meringkuk di balik kursi taman, berdoa agar Langit bisa memenangkan pertarungan mematikan ini."],
                    9 => ['title' => 'Bab 9 | Portal Galaksi', 'content' => "Ledakan cahaya menyilaukan mengakhiri pertarungan itu. Saat asap mengepul hilang, yn berteriak histeris. Langit sudah menghilang. Bayangan-bayangan itu berhasil meringkus Langit dan membawanya kembali ke dimensinya. yn berlari ke tengah kawah pertarungan, jatuh terduduk di atas tanah yang hangus, menangis sejadi-jadinya memanggil nama Langit.<br><br>Berhari-hari yn mengurung diri di kamar. Hampa. Seolah separuh jiwanya ikut diculik bersama Langit. Namun, yn teringat pada kalung kristal biru yang pernah Langit berikan kepadanya. Saat yn menggenggam kristal itu sambil menangis, kristal itu memancarkan proyeksi peta holografik di dinding kamar yn. Peta itu menunjukkan sebuah titik koordinat tersembunyi di bumi.<br><br>'Aku harus menyelamatkannya,' tekad yn bulat. Menghapus air matanya, yn mengemas barang-barang seperlunya ke dalam ransel. Mengikuti panduan cahaya dari kalung kristal, yn menempuh perjalanan jauh membelah hutan pinus, bertekad menemukan portal menuju galaksi demi membawa Langit kembali ke sisinya."],
                    10 => ['title' => 'Bab 10 | Dunia Terbalik', 'content' => "Titik koordinat itu membawa yn ke sebuah danau terlarang di pedalaman hutan yang belum terjamah manusia. Air danau itu tidak memantulkan bayangan bumi, melainkan memantulkan hamparan nebula berwarna ungu dan bintang-bintang raksasa. yn menelan ludah, meyakinkan dirinya sendiri sebelum akhirnya melompat terjun ke dalam danau tersebut.<br><br>Bukannya tenggelam, tubuh yn malah tersedot oleh pusaran energi yang hangat. Dalam sekejap, yn terlempar dan mendarat di atas permukaan kristal yang kokoh. yn berdiri dan terperangah. Dia berada di sebuah dunia yang terbalik. Bangunan-bangunan melayang di angkasa, air mengalir ke atas, dan langit dipenuhi oleh cahaya warna-warni yang memesona.<br><br>Namun, pemandangan indah itu tak menyurutkan fokus yn. Di kejauhan, di tengah alun-alun kristal utama, yn melihat sosok yang sangat dikenalnya. Langit terikat oleh rantai energi yang menyala panas. Di sekelilingnya, puluhan prajurit elit berpatroli ketat. Dengan jantung berpacu kencang, yn menyelinap diam-diam di balik pilar-pilar raksasa, menyusun rencana gila untuk membebaskan pujaan hatinya."],
                    11 => ['title' => 'Bab 11 | Pembebasan', 'content' => "Memanfaatkan kelengahan penjaga saat pergantian shift, yn berlari sekencang mungkin mendekati altar tempat Langit ditawan. Menggunakan kalung kristal biru yang bereaksi terhadap rantai energi, yn menempelkan kalung itu ke gembok magis. Terdengar bunyi desisan keras, dan rantai yang membelenggu Langit pun terlepas hancur berkeping-keping.<br><br>Langit jatuh berlutut, napasnya tersengal. Dia mendongak dan matanya terbelalak melihat siapa yang berdiri di depannya. 'Kau gila, yn! Kau bodoh sekali menyusulku ke tempat berbahaya ini!' bisik Langit marah, tapi suaranya bergetar karena khawatir, dan matanya berkaca-kaca menahan haru.<br><br>yn ikut berlutut, meraih wajah Langit dengan kedua tangannya. 'Aku tidak akan pernah meninggalkanmu sendirian di tempat dingin ini, Langit,' balas yn dengan tatapan tajam dan penuh keyakinan. Suara alarm tiba-tiba meraung-raung dari seluruh penjuru kota kristal. Pasukan elit telah menyadari pembobolan itu. Langit segera menarik tangan yn, dan mereka berdua berlari menerobos kerumunan prajurit yang mulai berdatangan."],
                    12 => ['title' => 'Bab 12 | Janji di Bawah Bintang', 'content' => "Berbekal sisa kekuatan Langit, mereka berhasil mencuri pesawat kecil pemburu dan kabur ke ujung galaksi, ke sebuah tempat tersembunyi tempat rasi bintang baru dilahirkan. Tempat itu sangat sunyi, hanya ada gumpalan debu bintang yang bersinar hangat seperti kunang-kunang di malam hari. Pesawat mereka mendarat di atas asteroid yang mengambang tenang.<br><br>Mereka duduk berdampingan di tepi asteroid, menatap hamparan semesta yang tak berujung. Langit menoleh, menatap yn dengan tatapan yang sangat dalam dan lembut. 'Aku selalu membenci takdirku sebagai pangeran bintang,' ucap Langit memecah keheningan. 'Tapi jika takdir itu yang membawaku jatuh ke halaman belakang rumahmu malam itu... aku bersyukur kepada semesta.'<br><br>yn tersenyum, matanya berkaca-kaca. Langit perlahan meraih jemari yn, menyentuhkan keningnya ke kening yn. 'yn, kau adalah satu-satunya alasan aku ingin menjadi manusia,' bisik Langit. Malam itu, di bawah saksi miliaran cahaya dari rasi bintang yang baru lahir, Langit dan yn saling mengikat janji suci sehidup semati, sebuah janji yang akan menentang hukum alam semesta."],
                    13 => ['title' => 'Bab 13 | Pengepungan', 'content' => "Namun pelarian romantis dan damai mereka tidak bertahan lama. Keberadaan kalung kristal di leher yn ternyata memancarkan sinyal pelacak. Saat mereka sedang terlelap di kabin pesawat, suara ledakan keras mengguncang asteroid. Pasukan elit raja bintang, yang dipimpin langsung oleh panglima tertinggi, telah mengepung tempat persembunyian mereka dari segala penjuru.<br><br>Langit menarik yn keluar dari pesawat yang terbakar. Ratusan prajurit mengacungkan senjata panah laser cahaya ke arah mereka. Langit mencoba melawan, tapi energi kosmiknya belum pulih sepenuhnya. Pertarungan berjalan berat sebelah.<br><br>Saat seorang prajurit menembakkan panah mematikan ke arah dada Langit, yn tanpa berpikir panjang melompat maju untuk menjadi tameng. Panah laser itu menembus bahu yn dengan telak. yn jatuh tersungkur, darah segar mengalir membasahi jaketnya. Teriakan pilu memanggil nama yn menggema di penjuru galaksi. Langit memeluk tubuh yn yang mulai melemah, matanya memerah menahan amarah yang meledak-ledak."],
                    14 => ['title' => 'Bab 14 | Sayap Cahaya', 'content' => "Melihat darah yn menetes dan menodai lantai asteroid, kesedihan Langit berubah menjadi murka yang tak terbendung. Segel ingatan dan kekuatan yang selama ini membelenggunya hancur berkeping-keping. Sebuah gelombang kejut energi raksasa meledak dari tubuh Langit, mementalkan seluruh prajurit elit yang mengepung mereka hingga puluhan meter ke belakang.<br><br>Dari punggung Langit, sepasang sayap cahaya raksasa yang sangat menyilaukan mengembang megah. Itu adalah bentuk tertinggi dari kekuatan pewaris tahta rasi bintang, kekuatan yang ditakuti oleh seluruh galaksi. Langit melayang di udara, matanya bersinar putih terang tanpa pupil. Suaranya menggema penuh ancaman, 'Kalian telah melukai satu-satunya hal yang berharga dalam hidupku.'<br><br>Langit mengamuk. Hanya dengan kibasan sayapnya, badai meteor dan badai plasma menghantam pasukan elit tanpa ampun. Dalam hitungan menit, armada yang tak terkalahkan itu hancur berantakan. Namun, di tengah kemenangan telaknya, Langit segera menarik kembali kekuatannya saat mendengar rintihan lemah dari mulut yn. Langit segera turun dan merengkuh tubuh yn yang semakin dingin."],
                    15 => ['title' => 'Bab 15 | Pengorbanan', 'content' => "Luka tembak dari panah laser cahaya itu bukanlah luka biasa; racun kosmiknya perlahan menggerogoti sel manusia di tubuh yn. Napas yn semakin putus-putus. Langit memacu pesawat tempur yang direbutnya dengan kecepatan maksimal, menembus lorong dimensi untuk membawa tubuh yn kembali ke bumi. Udara bumi adalah satu-satunya hal yang bisa memperlambat racun tersebut.<br><br>Sesampainya di halaman belakang rumah yn—tempat mereka pertama kali bertemu—Langit membaringkan yn di atas rerumputan. Keadaan yn sangat kritis, detak jantungnya nyaris tak terdengar. Langit menangis terisak, menggenggam tangan yn erat-erat. 'Jangan tinggalkan aku, yn. Ku mohon,' bisik Langit putus asa.<br><br>Menyadari tak ada lagi waktu untuk membawa yn ke rumah sakit, Langit membuat keputusan paling nekat dalam sejarah kaumnya. Langit menempelkan tangannya di atas dada yn, memejamkan mata, dan mulai mengucapkan mantra terlarang. Tanpa ragu sedikit pun, Langit mentransfer seluruh esensi keabadian dan energi kehidupan bintangnya ke dalam tubuh yn, demi menyembuhkan luka fatal yang merenggut nyawa gadis itu."],
                    16 => ['title' => 'Bab 16 | Kehilangan', 'content' => "Cahaya keemasan yang hangat menyelimuti tubuh yn. Racun kosmik itu menguap, dan luka di bahunya menutup dengan sempurna tanpa bekas. yn menarik napas panjang dan membuka matanya perlahan. Hal pertama yang dilihatnya adalah wajah Langit. Namun, senyum lega yn seketika sirna saat melihat keadaan pemuda itu.<br><br>Langit tergeletak di samping yn, napasnya tersengal parah. Kulitnya yang dulu bercahaya kini tampak pucat pasi layaknya mayat. Sayap cahaya agungnya telah lenyap, dan aura keabadiannya sirna tanpa sisa. yn panik luar biasa. 'Langit! Apa yang kau lakukan padat dirimu sendiri?!' tangis yn histeris, merengkuh kepala Langit ke pangkuannya.<br><br>Langit tersenyum lemah, menyeka air mata yn dengan tangannya yang kini terasa sedingin es. 'Aku... menukar keabadian dan kekuatanku... untuk hidupmu, yn,' bisik Langit dengan sisa tenaga terakhirnya. 'Bagiku, seribu tahun hidup sebagai dewa bintang tidak ada artinya jika... tidak ada kau di sisiku.' Tangis yn semakin pecah, memeluk tubuh Langit yang mulai kehilangan kehangatannya di tengah dinginnya malam bumi."],
                    17 => ['title' => 'Bab 17 | Murka Sang Raja', 'content' => "Tiba-tiba, langit malam di atas rumah yn bergemuruh hebat. Awan-awan tersibak dengan kasar, menampakkan sebuah kapal induk raksasa yang menutupi separuh langit kota. Cahaya sorot turun ke halaman belakang, membawa turun sosok pria paruh baya dengan aura kekuasaan yang luar biasa mencekam. Dia adalah Sang Raja Bintang, ayah kandung Langit.<br><br>Mata Sang Raja menyala penuh murka melihat putra mahkotanya terkapar sekarat layaknya manusia fana yang hina. 'Apa yang telah kau lakukan, bocah bodoh?!' bentak Sang Raja hingga bumi bergetar. Dia mengangkat tangannya, bersiap melenyapkan yn yang dianggap sebagai penyebab kehancuran putranya. 'Manusia rendahan ini tidak pantas menerima keabadianmu!'<br><br>Melihat ancaman itu, yn justru bangkit berdiri dan merentangkan kedua tangannya, melindungi tubuh Langit yang tak berdaya. 'Bunuh saja aku! Tapi tolong, selamatkan nyawanya! Kembalikan kekuatannya!' teriak yn di sela isak tangisnya. Keberanian yn menatap langsung mata Sang Raja membuat pria penguasa galaksi itu tertegun. Melihat air mata tulus dari yn dan pengorbanan suci putranya yang tanpa syarat, dinding es di hati Sang Raja perlahan mulai retak."],
                    18 => ['title' => 'Bab 18 | Kesepakatan', 'content' => "Sang Raja menurunkan tangannya perlahan. Dia berjalan mendekati tubuh Langit, menyalurkan setitik energi kosmik murni sekadar untuk menstabilkan detak jantung Langit agar tidak mati. Langit perlahan membuka matanya, menatap ayahnya dengan pandangan memohon, tangannya masih berusaha menggapai ujung baju yn.<br><br>'Cinta kalian telah merusak tatanan alam semesta,' ucap Sang Raja dengan suara berat dan dingin. Dia menatap yn dan Langit bergantian. 'Kau menolak tahta demi manusia ini. Baiklah. Kau boleh tinggal di bumi bersama gadis ini, Langit. Tapi ingat konsekuensinya.'<br><br>Sang Raja menancapkan tongkatnya ke tanah. 'Kau tidak akan pernah bisa kembali ke galaksi. Kau akan hidup sebagai manusia biasa yang rapuh. Kau akan menua, kau akan merasakan sakit, dan pada akhirnya... kau akan mati dan menjadi debu.' Langit tersenyum damai mendengar hukuman tersebut. Tanpa ragu sedikit pun, dia mengangguk pelan. 'Menjadi manusia yang bisa menua bersama yn... adalah anugerah terbesar bagiku, Ayah,' jawab Langit mantap."],
                    19 => ['title' => 'Bab 19 | Kehidupan Baru', 'content' => "Sang Raja berbalik, kembali ke kapalnya dan menghilang di balik awan malam, meninggalkan Langit dan yn untuk selama-lamanya. Keajaiban malam itu ditutup dengan pelukan erat di antara mereka berdua, sebuah babak baru yang terlahir dari pengorbanan cinta yang luar biasa. Hari-hari ajaib dan berbahaya mereka telah usai, berganti dengan kehidupan normal yang tenang.<br><br>Langit mulai belajar beradaptasi menjadi manusia sepenuhnya. Tentu saja, itu bukan hal yang mudah. Langit harus belajar menyeberang jalan tanpa menggunakan telepati, belajar menggunakan sumpit, dan bahkan dia sempat terserang demam pertamanya—sesuatu yang membuat yn sangat panik sekaligus geli karena Langit merengek seperti anak kecil saat disuntik dokter.<br><br>Namun, Langit menikmati setiap detik kehidupan barunya. Dia mencari pekerjaan paruh waktu di sebuah toko buku tua, mengumpulkan gajinya dengan sabar. Dia juga rajin belajar memasak melalui tutorial internet, meskipun dapur yn sering kali menjadi korban percobaan resepnya yang gagal. Bagi yn, melihat Langit tersenyum ceria dengan celemek yang penuh noda tepung jauh lebih membahagiakan daripada terbang di atas awan."],
                    20 => ['title' => 'Bab 20 | Selamanya', 'content' => "Satu tahun penuh telah berganti sejak malam Sang Raja datang. Musim semi menyapa kota dengan bunga-bunga yang bermekaran. Malam itu, Langit mengajak yn makan malam romantis di atap gedung yang dulu pernah menjadi tempat mereka pertama kali terbang. Lampu-lampu kota yang berkelap-kelip menjadi saksi bisu perjalanan panjang mereka.<br><br>Setelah menghabiskan hidangan penutup, Langit tiba-tiba bangkit dari kursinya. Di bawah tatapan langit malam yang cerah berbintang, Langit perlahan berlutut dengan satu kaki di hadapan yn. Jantung yn seketika berdebar kencang, persis seperti malam pertama kali mereka bertemu. Langit merogoh saku jasnya, mengeluarkan sebuah kotak beludru berwarna biru tua.<br><br>Saat kotak itu dibuka, tampak sebuah cincin indah yang bertahtakan satu-satunya sisa pecahan kristal bintang miliknya yang berkilau lembut. Langit menatap mata yn dengan penuh cinta dan ketulusan yang tak pernah pudar. 'Aku telah menukar seluruh keabadianku untuk bisa berdiri di sini sebagai pria biasa,' ucap Langit lembut. 'yn, maukah kau melengkapi sisa hidup sementaraku ini? Maukah kau menua bersamaku selamanya?' Air mata kebahagiaan yn tumpah seketika seiring dengan anggukan kepala yang akan mengikat takdir mereka abadi di bumi."]
                ]
            ],
            '4' => [
                'title' => 'Hujan Sore',
                'author' => 'Tipnaree Racha',
                'cover' => 'https://picsum.photos/seed/naratia3/150/220',
                'chapters' => [
                    1 => ['title' => 'Bab 1 | Rintik Pertama', 'content' => "Gerimis mulai turun saat bel sekolah berbunyi nyaring. yn menghela napas panjang menatap ke luar jendela kelas yang mulai berembun. Lupa membawa payung adalah kebiasaan buruk yang belum bisa yn hilangkan. Murid-murid lain berlarian mencari tempat berteduh, tapi yn hanya diam terpaku di ambang pintu.<br><br>Angin sore berhembus cukup kencang, membuat yn merapatkan seragamnya. yn menatap rintik hujan yang semakin menderas membasahi aspal lapangan basket. 'Sial sekali nasibku hari ini,' batin yn merana. Hujan perlahan menjelma menjadi tirai air yang menghalangi pandangan yn ke gerbang sekolah.<br><br>Sambil menunggu, yn membuka ponselnya, berharap ada pesan dari seseorang yang bisa dimintai tolong. Kosong. Tiba-tiba, suara cipratan air dari langkah kaki terdengar mendekat. yn menoleh perlahan, berharap keajaiban datang menjemputnya sore itu."],
                    2 => ['title' => 'Bab 2 | Payung Merah', 'content' => "Saat yn bersiap untuk menerobos hujan berlari ke halte bus karena sekolah sudah mulai sepi, tiba-tiba sebuah payung merah terulur melindunginya dari rintikan air. yn terkesiap, mundur selangkah karena terkejut.<br><br>'Bisa sakit kalau memaksakan diri, yn,' ucap sebuah suara lembut dari sampingnya. yn menoleh dan mendapati Elgano, teman sekelasnya yang super pendiam, berdiri di sana dengan senyum canggung. Pipi yn seketika merona merah menyadari jarak mereka yang begitu dekat.<br><br>'Eh, El? Kamu belum pulang?' tanya yn gugup. El menggeleng pelan. 'Menunggumu,' jawabnya singkat namun sukses membuat jantung yn berdebar dua kali lebih cepat dari biasanya."],
                    3 => ['title' => 'Bab 3 | Halte Kenangan', 'content' => "Mereka berjalan berdua di bawah satu payung merah menuju halte bus di ujung jalan. Jarak bahu mereka begitu dekat hingga yn bisa mencium aroma maskulin bercampur sabun mandi dari kemeja El. Sepanjang jalan, yn hanya diam menunduk, takut wajahnya yang merona ketahuan.<br><br>Sesampainya di halte, jalanan sangat sepi. Papan jadwal elektronik menunjukkan bahwa bus terakhir ternyata sudah lewat lima menit yang lalu. yn menghela napas frustrasi, bahunya turun menyadari mereka terjebak.<br><br>'Sepertinya kita harus menunggu hujan reda, yn,' ujar El santai sambil melipat payung merahnya yang basah kuyup. Dia menatap yn dengan pandangan teduh, membuat yn entah kenapa tidak merasa kesal sama sekali terjebak di halte tua ini."],
                    4 => ['title' => 'Bab 4 | Secangkir Cokelat Panas', 'content' => "Suhu udara semakin dingin, menusuk hingga ke tulang. Melihat tubuh yn yang sedikit menggigil dan terus menggosok telapak tangan, El tiba-tiba melepas jaket almamaternya dan menyampirkannya ke bahu yn tanpa permisi.<br><br>'El, jangan, nanti kamu kedinginan,' tolak yn halus, meski sejujurnya jaket itu sangat hangat dan wangi. El hanya tersenyum kecil lalu berlari menerobos gerimis ke sebuah minimarket yang ada di seberang jalan.<br><br>Tak lama, El kembali dengan rambut setengah basah, membawa dua gelas kertas berisi cokelat panas yang masih mengepul. 'Minumlah, yn. Biar tubuhmu sedikit hangat,' ucapnya sambil mengusap air hujan dari rambutnya. yn menerima gelas itu dengan hati yang ikut menghangat."],
                    5 => ['title' => 'Bab 5 | Obrolan Ringan', 'content' => "Sambil menyesap cokelat panas, mereka berdua duduk berdampingan di bangku halte kayu yang mulai lapuk. Awalnya sangat canggung, tapi perlahan, ditemani suara rintik hujan, mereka mulai mengobrol ringan. yn menceritakan keluh kesahnya tentang tugas matematika yang menumpuk.<br><br>El mendengarkan dengan saksama, sesekali menimpali dengan lelucon cerdas yang membuat yn tertawa lepas. yn baru menyadari bahwa pemuda pendiam di kelasnya ini ternyata memiliki selera humor yang sangat bagus dan wawasan yang luas.<br><br>Tawa yn mengudara, mengalahkan suara rintik hujan sore itu. El menatap yn lekat-lekat, senyum tak pernah luntur dari bibirnya. Di momen itu, yn merasa halte bus tua ini adalah tempat paling nyaman di dunia."],
                    6 => ['title' => 'Bab 6 | Genangan Air', 'content' => "Hujan tak kunjung reda meski langit perlahan mulai menggelap menjadi ungu pekat. Tiba-tiba, sebuah mobil sedan melaju sangat kencang melewati genangan air berlumpur tepat di depan halte, menyipratkan air kotor ke arah tempat yn duduk.<br><br>Kejadiannya sangat cepat. Dengan gerakan refleks yang luar biasa sigap, El menarik lengan yn keras-keras dan membalikkan badannya, melindungi tubuh yn dari cipratan air kotor tersebut dengan punggungnya sendiri.<br><br>Cipratan air kotor itu mengenai punggung kemeja El, namun yn sama sekali tidak tersentuh setetes pun berkat perlindungan pemuda itu. yn membelalakkan matanya, terkejut dengan tindakan heroik El yang tiba-tiba."],
                    7 => ['title' => 'Bab 7 | Jarak yang Menipis', 'content' => "Tarikan spontan itu membuat tubuh yn menabrak pelan dada El. Selama beberapa detik yang terasa seperti selamanya, wajah mereka hanya berjarak beberapa senti. yn menahan napas, menatap langsung ke dalam manik mata El yang berwarna kecoklatan di bawah keremangan lampu jalan.<br><br>Waktu seolah berhenti berputar. yn bisa merasakan hembusan napas El yang hangat menerpa wajahnya. Jantung yn berdetak brutal, seakan ingin melompat keluar dari rongga dadanya saat itu juga.<br><br>Menyadari posisi mereka yang kelewat intim, El buru-buru melepaskan pegangannya pada bahu yn sambil berdehem canggung. 'Maaf, yn. Aku refleks,' gumamnya memalingkan wajah, menyembunyikan telinganya yang memerah."],
                    8 => ['title' => 'Bab 8 | Menggigil', 'content' => "Karena melindungi yn tadi, kemeja seragam El kini basah dan kotor. Angin malam yang berhembus membuat pemuda itu mulai bersin-bersin pelan. yn merasa bersalah luar biasa melihat El menggigil kedinginan.<br><br>'El, kau kedinginan karena aku,' gumam yn khawatir dengan mata berkaca-kaca. yn segera melepas jaket almamater yang dipinjamkannya dan memaksa memakaikannya kembali ke punggung El.<br><br>Namun, El menahannya. Dia menggenggam tangan yn yang dingin. 'Pakai saja, yn. Aku sudah terbiasa dengan hawa dingin. Melihatmu kedinginan jauh lebih menyiksaku,' balasnya dengan suara serak yang membuat hati yn meleleh seketika."],
                    9 => ['title' => 'Bab 9 | Berbagi Earphone', 'content' => "Untuk mengusir rasa dingin dan kecanggungan di antara mereka, El mengeluarkan earphone kabel dari saku celananya. Dia memasangkan satu sisi ke telinga kirinya, lalu menyodorkan sisi kanan ke arah yn dengan senyum tipis.<br><br>yn menerimanya dengan ragu. Saat earphone itu terpasang, alunan lagu indie akustik yang menenangkan mengalun perlahan. Liriknya seolah menggambarkan suasana hati yn saat ini.<br><br>Mereka duduk bersisian dalam diam, berbagi musik yang sama, terhubung oleh seutas kabel kecil. Perasaan yn membuncah. Keheningan yang tercipta di antara yn dan El kini terasa sangat nyaman, diiringi melodi hujan yang tak kunjung henti."],
                    10 => ['title' => 'Bab 10 | Tertidur', 'content' => "Rasa lelah belajar seharian, udara yang teramat dingin, dan alunan musik yang menenangkan membuat rasa kantuk yn perlahan tak tertahankan. Kelopak mata yn semakin berat, berulang kali terbuka dan terpejam.<br><br>Tanpa sadar, kepala yn perlahan miring ke samping dan bersandar nyaman di bahu kokoh El. Saat bersentuhan, pemuda itu terkejut sejenak, tubuhnya sempat menegang kaku selama beberapa detik.<br><br>Namun, melihat wajah yn yang tertidur pulas dengan damai, El tersenyum sangat tulus. Dia membiarkan yn tertidur lelap bersandar padanya, tak berani bergerak sedikit pun agar tidur yn tidak terganggu. Tangan El diam-diam merapatkan jaket di tubuh yn."],
                    11 => ['title' => 'Bab 11 | Pelangi', 'content' => "Satu jam berlalu, rintik hujan akhirnya reda sepenuhnya. Semburat matahari senja muncul dari balik awan kelabu di ufuk barat, membiaskan cahaya keemasan yang menciptakan busur pelangi melengkung indah di atas deretan ruko.<br><br>El menepuk pelan bahu yn dengan lembut. 'yn, bangunlah. Hujannya sudah reda,' bisiknya tepat di telinga yn. yn mengerjap pelan, mengusap matanya yang masih mengantuk dan langsung panik menyadari dia tertidur di bahu El.<br><br>'Ya ampun, maaf El! Bahumu pasti pegal,' seru yn panik. El hanya tertawa renyah sambil menunjuk ke langit. 'Tidak apa-apa, yn. Lihat ke atas, ada pelangi yang menunggumu bangun.'"],
                    12 => ['title' => 'Bab 12 | Taksi Tua', 'content' => "Karena jadwal bus sudah dipastikan tidak ada lagi, mereka berdua akhirnya memutuskan untuk mencegat sebuah taksi tua yang kebetulan lewat perlahan di depan halte. Mereka masuk ke kursi belakang bersama-sama.<br><br>Di dalam taksi, mereka duduk bersebelahan, memandang ke luar jendela yang masih basah. Tak ada lagi percakapan panjang, namun senyum kecil tak pernah luntur dari bibir yn. Hatinya dipenuhi gelembung-gelembung kebahagiaan yang sulit dijelaskan.<br><br>Momen hujan sore, halte sepi, secangkir cokelat panas, dan bahu El yang nyaman itu begitu membekas kuat dalam ingatan yn. yn berharap perjalanan pulang ini terasa sedikit lebih lambat."],
                    13 => ['title' => 'Bab 13 | Di Depan Rumah', 'content' => "Taksi akhirnya berhenti tepat di depan pagar rumah yn yang sepi. yn turun perlahan, berbalik menghadap kaca taksi yang terbuka tempat El duduk. Udara sehabis hujan terasa sangat segar menyapu wajah yn.<br><br>'Terima kasih banyak untuk hari ini, El. Dan untuk payungnya, untuk cokelat panasnya, semuanya,' ucap yn tulus sambil menyerahkan kembali jaket almamater El yang wangi.<br><br>El mengangguk lembut sambil memegang gagang payung merahnya di pangkuan. 'Sama-sama, yn. Langsung mandi air hangat ya, jangan sampai sakit. Sampai jumpa besok di kelas.' Taksi itu berlalu, meninggalkan yn yang masih tersenyum sendiri di depan pagar."],
                    14 => ['title' => 'Bab 14 | Demam Rindu', 'content' => "Keesokan harinya, pemuda berpayung merah itu tidak masuk sekolah. Kabar beredar dari wali kelas bahwa El jatuh sakit dan demam parah karena kehujanan. Mendengar itu, hati yn mencelos jatuh ke dasar lantai. Rasa bersalah menghantam dada yn dengan keras.<br><br>Sepanjang jam pelajaran sekolah, yn sama sekali tak bisa fokus. Mata yn terus saja mencuri pandang ke arah bangku kosong di sudut kelas belakang, tempat El biasa duduk menopang dagu.<br><br>Pikiran yn kalut. Saat jam istirahat, yn nekat menanyakan alamat rumah El kepada ketua kelas. yn bertekad kuat, apa pun yang terjadi, yn harus menjenguk El sepulang sekolah nanti. yn harus merawat pemuda yang telah melindunginya itu."],
                    15 => ['title' => 'Bab 15 | Payung Kembar', 'content' => "Sore itu, saat yn berdiri ragu memencet bel di depan rumah El, gerimis kembali turun perlahan membasahi bumi. Mengulang memori kemarin sore. Namun yn tersenyum kecil menatap rintik air itu. Berbeda dengan kemarin, kali ini yn sudah sangat siap.<br><br>yn membuka payung miliknya sendiri, sebuah payung berwarna biru terang, bersiap memayungi El jika pemuda itu membukakan pintu. Tak lama, pintu terbuka, menampakkan El yang pucat namun langsung tersenyum cerah melihat siapa yang datang.<br><br>'Aku membawa sup hangat untukmu,' ucap yn dengan rona merah di pipi. Kisah mereka yang bermula dari ketidaksengajaan di bawah hujan sore kemarin, tampaknya baru akan memasuki babak baru yang jauh lebih manis dan menghangatkan hati."]
                ]
            ],
            '5' => [
                'title' => 'Misteri Kelas',
                'author' => 'Dee Lestari',
                'cover' => 'https://picsum.photos/seed/naratia4/150/220',
                'chapters' => [
                    1 => ['title' => 'Bab 1 | Kutukan Loker 13', 'content' => "Bel pulang sekolah sudah berbunyi nyaring sejak dua jam yang lalu, tapi yn masih berkutat sendirian dengan setumpuk buku tugas sejarah di sudut perpustakaan. Konon, SMA tempat yn bersekolah ini menyimpan banyak legenda urban kelam yang dirahasiakan rapat-rapat oleh pihak guru.<br><br>Salah satu yang paling mengerikan adalah mitos tentang loker nomor 13 yang berada di koridor sayap barat lantai dua. Menurut desas-desus angkatan atas, loker itu dikutuk. Siapapun murid yang berani membuka loker tersebut setelah matahari terbenam, arwahnya akan ditarik ke dimensi lain dan tak akan pernah terlihat lagi.<br><br>yn selalu menganggap itu hanya cerita karangan untuk menakut-nakuti siswa agar tidak keluyuran malam-malam. Namun, saat penjaga sekolah mematikan lampu perpustakaan, menandakan yn harus segera pulang, bulu kuduk yn tiba-tiba meremang tanpa alasan yang jelas."],
                    2 => ['title' => 'Bab 2 | Tertinggal', 'content' => "Dengan langkah buru-buru, yn mengemasi bukunya. Sialnya, saat merogoh saku, yn baru menyadari bahwa kunci rumahnya tertinggal di laci meja kelas. yn menggerutu kesal. Mau tidak mau, yn harus kembali naik ke lantai dua yang kini sudah gelap gulita.<br><br>Dengan perasaan was-was dan hanya mengandalkan cahaya senter dari ponselnya, yn berjalan menyusuri koridor. Suara langkah sepatunya menggema menakutkan di dinding lorong. Hawa dingin tiba-tiba berhembus menyapu tengkuk yn, padahal semua jendela tertutup rapat.<br><br>Saat yn melewati deretan loker sayap barat, entah dorongan aneh dari mana, langkah yn terhenti. Cahaya senter yn perlahan menyorot ke arah deretan loker berkarat itu. Mata yn tertuju pada pintu loker nomor 13 yang, anehnya, malam itu terbuka menganga sedikit."],
                    3 => ['title' => 'Bab 3 | Buku Harian', 'content' => "Didorong oleh rasa penasaran yang mendadak mengalahkan akal sehat dan rasa takutnya, yn melangkah pelan mendekati loker terkutuk itu. Tangan yn yang gemetar perlahan meraih gagang pintu dan membukanya lebih lebar. Engsel berkarat itu berderit memekakkan telinga.<br><br>Di dalam loker yang pengap itu, tidak ada monster atau hantu seperti yang ditakutkan yn. Hanya ada debu tebal dan sebuah buku bersampul kulit hitam lusuh tergeletak di sudutnya. yn mengambilnya perlahan, meniup debu di sampulnya hingga membuat yn terbatuk.<br><br>Saat yn menyinari halaman pertama buku itu, jantung yn berdegup kencang. Tertulis rapi dengan tinta merah pudar: 'Milik Arjuna'. yn menelan ludah. Arjuna adalah nama murid jenius teladan yang fotonya terpajang di mading, murid yang dinyatakan hilang tanpa jejak tepat lima tahun yang lalu."],
                    4 => ['title' => 'Bab 4 | Tulisan Berdarah', 'content' => "Penyakit penasaran yn semakin menjadi-jadi. Berbekal cahaya redup ponsel, yn membuka halaman demi halaman buku harian Arjuna. Isinya sungguh mengejutkan. Arjuna mencatat secara detail tentang ritual rahasia dan sekte gelap yang dilakukan oleh kepala sekolah di rubanah gedung ini setiap bulan purnama.<br><br>Namun di sepuluh halaman terakhir, bentuk tulisan Arjuna berubah drastis menjadi acak-acakan dan ditekan sangat keras hingga merobek kertas, seolah ditulis dalam keadaan panik yang luar biasa dan dikejar waktu.<br><br>Halaman terakhir membuat napas yn tercekat. Tertulis dengan cairan kental berwarna merah kecoklatan: 'Mereka tahu aku menemukannya. Mereka datang menjemputku malam ini. LARI.' Tulisan berdarah itu membuat yn bergidik ngeri, seakan pesan itu ditujukan langsung untuk yn malam ini."],
                    5 => ['title' => 'Bab 5 | Langkah Kaki', 'content' => "Tiba-tiba, dari arah ujung koridor gelap tempat tangga berada, terdengar suara langkah kaki berat. Tap... tap... tap... Suaranya berjalan sangat lambat dan menyeret, namun pasti menuju ke arah tempat yn berdiri membeku.<br><br>Kepanikan luar biasa melanda yn. Tubuhnya gemetar hebat, keringat dingin membasahi pelipisnya. 'Ada yang datang,' batin yn histeris. Mengikuti insting bertahan hidup, yn segera memasukkan buku harian kulit hitam itu ke dalam ranselnya.<br><br>Tanpa mematikan senter ponsel, yn berlari terbirit-birit menelusuri lorong menjauhi suara langkah itu. yn menerobos masuk dan bersembunyi di dalam ruang kelas 11-B, kelas lamanya yang kebetulan pintunya tidak dikunci oleh petugas kebersihan."],
                    6 => ['title' => 'Bab 6 | Mengintip', 'content' => "yn segera mematikan layar ponselnya dan meringkuk gemetar di kolong bawah meja guru di depan kelas, menutup mulut dan hidungnya erat-erat dengan kedua tangan menahan suara napasnya sendiri yang memburu.<br><br>Dari kolong meja, yn menatap lekat ke arah celah bawah pintu kelas. Suara langkah kaki menyeret itu semakin dekat, dan akhirnya berhenti tepat di depan pintu kelas 11-B. Bayangan hitam sepasang kaki besar tercetak jelas dari celah cahaya bulan yang masuk menembus jendela lorong.<br><br>yn memejamkan mata rapat-rapat sambil merapalkan segala doa yang ia tahu. Terdengar suara derit engsel gagang pintu yang diputar perlahan dari luar. Pintu kelas 11-B dibuka secara paksa, menimbulkan suara decitan yang membuat ngilu telinga yn."],
                    7 => ['title' => 'Bab 7 | Gelap', 'content' => "Lampu neon panjang di koridor luar tiba-tiba berkedip-kedip sebelum akhirnya mati total dengan suara konsleting. Kegelapan mutlak kini menyelimuti seluruh ruangan. yn menelan ludah, matanya mencoba membiasakan diri dalam gelap gulita.<br><br>Di tengah kesunyian yang mencekam itu, yn mendengar suara napas yang sangat berat, serak, dan berlendir, seakan sosok itu menderita asma akut. Seseorang, atau sesuatu, kini telah melangkah masuk dan mulai berjalan pelan mengelilingi deretan meja murid, mencari keberadaan yn di sana.<br><br>Suara kursi yang digeser kasar dan meja yang digebrak membuat yn berkali-kali berjengit kaget. Sosok itu terus berjalan mendekati area depan kelas, tempat meja guru tempat yn bersembunyi berada. yn tahu, waktunya sudah tidak banyak lagi."],
                    8 => ['title' => 'Bab 8 | Bisikan', 'content' => "Langkah kaki menyeret itu akhirnya berhenti tepat di samping meja kayu besar tempat yn meringkuk. Ujung sepatu hitam berlumpur terlihat jelas dalam jarak beberapa sentimeter dari wajah yn. Hening sejenak. Sangat hening hingga yn bisa mendengar detak jantungnya sendiri.<br><br>yn mengira sosok itu akan berbalik pergi. Namun kemudian, dari arah celah kolong meja tepat di atas telinga yn, sebuah suara bisikan terdengar begitu dekat menyapu rambut yn. Baunya sangat busuk seperti daging busuk.<br><br>'Sedang membaca rahasia kami, yn? Kembalikan buku itu...' Suara itu memanggil nama yn. yn membeku total. Itu bukan suara penjaga sekolah. Itu adalah suara berat dan parau yang terdengar seolah berasal dari dasar sumur. Ia tahu yn ada di bawah sini."],
                    9 => ['title' => 'Bab 9 | Pelarian', 'content' => "Mengetahui keberadaannya sudah ketahuan, adrenalin mengambil alih seluruh fungsi tubuh yn. Dengan sisa keberanian yang ada, yn menjerit sekencang-kencangnya. yn menendang kursi guru ke arah bayangan hitam di depannya hingga sosok itu terhuyung mundur.<br><br>Tanpa menoleh ke belakang sedetik pun, yn merangkak keluar dari kolong meja, bangkit berdiri, dan berlari sekuat tenaga menabrak pintu kelas hingga terbuka lebar. yn berlari kalang kabut menyusuri lorong koridor, mengabaikan barang-barang di ranselnya yang berjatuhan.<br><br>Suara geraman buas terdengar mengejar tepat di belakang yn. yn menuruni anak tangga dengan melompat membabi buta dalam kegelapan, menerjang pintu utama sekolah yang digembok tebal. yn harus segera keluar dari pekarangan neraka ini sebelum sosok itu menangkapnya."],
                    10 => ['title' => 'Bab 10 | Mengungkap', 'content' => "Menyadari gerbang utama digembok berlapis, yn beralih berlari ke pagar tembok samping sekolah. Dengan napas tersengal dan sisa tenaga terakhirnya, yn memanjat tembok bata yang kasar, tidak mempedulikan telapak tangannya yang lecet berdarah.<br><br>yn berhasil melompat keluar ke trotoar jalanan sesaat sebelum sebuah tangan pucat sedingin es dari bayangan hitam itu menggapai pergelangan kakinya. Jatuh terduduk di bawah terang lampu jalanan yang aman, yn terengah-engah menatap pagar sekolah yang kini kembali sunyi seolah tak terjadi apa-apa.<br><br>Sambil bersandar di tiang lampu, yn merogoh saku seragamnya dengan tangan gemetar. Buku harian kulit hitam itu ternyata masih selamat ada di sana. yn memeluk buku itu erat-erat di dadanya. Malam ini yn selamat, namun yn bertekad bulat, misteri kutukan sekolah berdarah ini harus ia ungkap ke polisi keesokan paginya."]
                ]
            ]
        ];

        // LOGIKA PENANGANAN BAB DAN SULAP NAMA KARAKTER
        $storyData = $story[$storyId] ?? $story['1'];
        $maxChap = count($storyData['chapters']);
        
        if($currentChapter < 1) $currentChapter = 1;
        if($currentChapter > $maxChap) $currentChapter = $maxChap;

        $chapterData = $storyData['chapters'][$currentChapter];
        $chapterTitle = $chapterData['title'];
        $rawContent = $chapterData['content'];

        $processedContent = preg_replace('/\byn\b/i', "<span class='text-indigo-400 font-bold'>$charName</span>", $rawContent);
    @endphp

    <!-- TOP BAR -->
    <header class="sticky top-0 bg-[#02040f]/90 backdrop-blur-md border-b border-white/10 p-4 flex items-center justify-between z-20 shadow-lg">
        <!-- TOMBOL KEMBALI MENGARAH KE LIBRARY -->
        <a href="/library" class="p-2.5 bg-white/5 hover:bg-white/10 rounded-full transition border border-white/10">
            <img src="https://img.icons8.com/ios-filled/24/ffffff/left.png" class="w-4 h-4"/>
        </a>
        
        <div class="text-center">
            <h1 class="text-[10px] font-bold uppercase tracking-widest text-gray-500">{{ $storyData['title'] }}</h1>
            <h2 class="text-sm font-semibold text-white mt-0.5">{{ $chapterTitle }}</h2>
        </div>
        
        <button id="open-chapter-btn" class="p-2.5 bg-white/5 hover:bg-white/10 rounded-full transition border border-white/10">
            <img src="https://img.icons8.com/ios-filled/24/ffffff/menu-2.png" class="w-4 h-4"/>
        </button>
    </header>

    <!-- OVERLAY GELAP UNTUK SIDEBAR -->
    <div id="sidebar-overlay" class="fixed inset-0 bg-black/60 backdrop-blur-sm z-30 hidden transition-opacity opacity-0"></div>

    <!-- SIDEBAR DAFTAR BAB -->
    <aside id="chapter-sidebar" class="fixed top-0 right-0 h-full w-[80%] max-w-sm bg-[#1a1c29] z-40 transform translate-x-full transition-transform duration-300 shadow-2xl flex flex-col border-l border-white/10">
        
        <div class="p-4 flex justify-between items-center border-b border-white/5 shrink-0">
            <h3 class="text-xs font-bold text-gray-400 uppercase tracking-widest">Daftar Isi</h3>
            <button id="close-chapter-btn" class="p-2 hover:bg-white/10 rounded-full transition">
                <img src="https://img.icons8.com/ios-filled/20/ffffff/delete-sign.png" class="w-4 h-4"/>
            </button>
        </div>
        
        <div class="p-6 flex flex-col items-center border-b border-white/5 bg-black/20 shrink-0">
            <img src="{{ $storyData['cover'] }}" class="w-28 h-40 object-cover rounded-md shadow-xl mb-4 border border-white/10">
<h2 class="text-sm font-bold text-white text-center uppercase tracking-wider mb-1">{{ $storyData['title'] }}</h2>
<p class="text-xs text-indigo-300">{{ $storyData['author'] }}</p>
        </div>

        <div class="p-4 flex flex-col gap-1 overflow-y-auto no-scrollbar pb-20">
            @foreach($storyData['chapters'] as $num => $data)
                <a href="/stories/read/{{ $storyId }}?chapter={{ $num }}" class="px-4 py-3 rounded-lg text-sm transition {{ $num === $currentChapter ? 'font-bold text-indigo-400 bg-indigo-500/10 border-l-4 border-indigo-400' : 'font-semibold text-gray-400 hover:bg-white/5 hover:text-white' }}">
                    {{ $data['title'] }}
                </a>
            @endforeach
        </div>
    </aside>

    <!-- KONTEN CERITA -->
    <main class="flex-grow max-w-2xl mx-auto px-6 py-10 w-full mb-16">
        <div class="story-content text-gray-300 text-justify">
            {!! $processedContent !!}
        </div>
    </main>

    <!-- BOTTOM BAR NAVIGASI BAB -->
    <footer class="bg-[#0a0f1d] border-t border-white/10 p-5 flex justify-between items-center fixed bottom-0 w-full z-20">
        
        @if($currentChapter > 1)
            <a href="/stories/read/{{ $storyId }}?chapter={{ $currentChapter - 1 }}" class="px-5 py-2.5 bg-white/5 hover:bg-white/10 rounded-xl text-xs font-bold text-gray-400 transition">
                &laquo; Sebelumnya
            </a>
        @else
            <div></div> 
        @endif

        @if($currentChapter < $maxChap)
            <a href="/stories/read/{{ $storyId }}?chapter={{ $currentChapter + 1 }}" class="px-5 py-2.5 bg-indigo-600/80 hover:bg-indigo-500 rounded-xl text-xs font-bold text-white transition shadow-[0_0_15px_rgba(79,70,229,0.4)]">
                Selanjutnya &raquo;
            </a>
        @endif

    </footer>

    <!-- SCRIPT SIDEBAR -->
    <script>
        const openBtn = document.getElementById('open-chapter-btn');
        const closeBtn = document.getElementById('close-chapter-btn');
        const sidebar = document.getElementById('chapter-sidebar');
        const overlay = document.getElementById('sidebar-overlay');

        function openSidebar() {
            sidebar.classList.remove('translate-x-full');
            overlay.classList.remove('hidden');
            setTimeout(() => overlay.classList.remove('opacity-0'), 10);
        }

        function closeSidebar() {
            sidebar.classList.add('translate-x-full');
            overlay.classList.add('opacity-0');
            setTimeout(() => overlay.classList.add('hidden'), 300);
        }

        openBtn.addEventListener('click', openSidebar);
        closeBtn.addEventListener('click', closeSidebar);
        overlay.addEventListener('click', closeSidebar);
    </script>
</body>
</html>